// src/App.tsx
import React, { useCallback, useMemo, useState } from 'react';
import axios from 'axios';
import { useJsApiLoader } from '@react-google-maps/api';
import MapApp from './components/MapApp';
import LocTable from './components/LocTable';
import PlaceAutocomplete, { SelectedPlace } from './components/PlaceAutocomplete';
import { LatLng, LocationItem } from './types';

const env = (import.meta as ImportMeta & { env: Record<string, string | undefined> }).env;
const GOOGLE_MAP_API_KEY = env.VITE_GOOGLE_MAPS_API_KEY ?? env.REACT_APP_GOOGLE_MAPS_API_KEY ?? '';
const GOOGLE_MAPS_API_URL =
  env.VITE_GOOGLE_MAPS_API_URL ??
  env.REACT_APP_GOOGLE_MAPS_API_URL ??
  'https://maps.googleapis.com/maps/api';
const libraries: 'places'[] = ['places'];

type TimeData = {
  timeZoneName: string;
  localTimeStr: string;
};

function App(): React.ReactElement | null {
  const [selectedPlace, setSelectedPlace] = useState<SelectedPlace | null>(null);
  const [locItems, setLocItems] = useState<LocationItem[]>([]);
  const [center, setCenter] = useState<LatLng>({ lat: 43.653226, lng: -79.3831843 });
  const [warningMsg, setWarningMsg] = useState(false);
  const [isDarkMode, setIsDarkMode] = useState(false);

  const { isLoaded } = useJsApiLoader({
    id: 'google-map-script',
    googleMapsApiKey: GOOGLE_MAP_API_KEY,
    libraries,
  });

  const canDelete = useMemo(
    () => locItems.some((item: LocationItem) => item.checked),
    [locItems]
  );

  const handlePlaceSelect = useCallback((place: SelectedPlace): void => {
    setSelectedPlace(place);
    setWarningMsg(false);
  }, []);

  const getCoordinates = () =>
    new Promise<GeolocationPosition>((resolve, reject) => {
      navigator.geolocation.getCurrentPosition(resolve, reject);
    });

  const getTimeData = async (pos: LatLng): Promise<TimeData> => {
    const now = Math.floor(Date.now() / 1000);
    const { data: timezone } = await axios.get(
      `${GOOGLE_MAPS_API_URL}/timezone/json?location=${pos.lat},${pos.lng}&timestamp=${now}&key=${GOOGLE_MAP_API_KEY}`
    );
    const { timeZoneName, dstOffset, rawOffset } = timezone;
    const localTime = new Date((now + dstOffset + rawOffset) * 1000);
    const localTimeStr = `${localTime
      .getUTCHours()
      .toString()
      .padStart(2, '0')}:${localTime
      .getUTCMinutes()
      .toString()
      .padStart(2, '0')}`;

    return { timeZoneName, localTimeStr };
  };

  const getCurrentPosition = async (): Promise<void> => {
    if (!navigator.geolocation) {
      console.error('Geolocation is not supported by this browser.');
      return;
    }

    const { coords } = await getCoordinates();
    const pos: LatLng = { lat: coords.latitude, lng: coords.longitude };

    const { data: currLocData } = await axios.get(
      `${GOOGLE_MAPS_API_URL}/geocode/json?latlng=${pos.lat},${pos.lng}&key=${GOOGLE_MAP_API_KEY}`
    );
    const { timeZoneName, localTimeStr } = await getTimeData(pos);

    setLocItems((prev: LocationItem[]) => [
      ...prev,
      {
        locName: currLocData.results[0].formatted_address,
        pos,
        timeZoneName,
        localTimeStr,
        checked: false,
      },
    ]);
    setCenter(pos);
  };

  const addLoc = async (): Promise<void> => {
    if (selectedPlace) {
      const { name: placeName, pos } = selectedPlace;
      const { timeZoneName, localTimeStr } = await getTimeData(pos);

      setLocItems((prev: LocationItem[]) => [
        ...prev,
        {
          locName: placeName,
          pos,
          timeZoneName,
          localTimeStr,
          checked: false,
        },
      ]);
      setCenter(pos);
      setSelectedPlace(null);
      return;
    }

    setWarningMsg(true);
    setTimeout(() => setWarningMsg(false), 5000);
  };

  const delLoc = (): void => {
    setLocItems((prev: LocationItem[]) => prev.filter((item) => !item.checked));
  };

  const toggleLocChecked = (index: number): void => {
    setLocItems((prev: LocationItem[]) =>
      prev.map((item, itemIndex) =>
        itemIndex === index ? { ...item, checked: !item.checked } : item
      )
    );
  };

  if (!isLoaded) {
    return null;
  }

  return (
    <div className={`app-shell ${isDarkMode ? 'theme-dark' : 'theme-light'}`}>
      <div className="padCom">
        <div className="header-row">
          <h1 className="app-title">Location App</h1>
          <button
            className="btn btn-outline-secondary theme-toggle-btn"
            type="button"
            onClick={() => setIsDarkMode((prev) => !prev)}
            aria-label={isDarkMode ? 'Switch to light mode' : 'Switch to dark mode'}
            title={isDarkMode ? 'Switch to light mode' : 'Switch to dark mode'}
          >
            {isDarkMode ? '☀️' : '🌙'}
          </button>
        </div>
        <div className="input-group mb-3">
          <PlaceAutocomplete
            isLoaded={isLoaded}
            onPlaceSelect={handlePlaceSelect}
            isDarkMode={isDarkMode}
          />
          <button
            className="btn btn-outline-primary"
            type="button"
            onClick={() => void addLoc()}
          >
            Add Location
          </button>
          <button
            className="btn btn-outline-secondary"
            type="button"
            onClick={() => void getCurrentPosition()}
          >
            Get Current Posistion
          </button>
        </div>
        <div
          className={`alert alert-warning align-items-center ${
            warningMsg ? 'd-flex' : 'd-none'
          }`}
          role="alert"
        >
          Location entered is not found. Please select a location from dropdown
        </div>
      </div>
      <MapApp items={locItems} center={center} isDarkMode={isDarkMode} />
      <LocTable
        items={locItems}
        onDeleteSelected={delLoc}
        onToggleChecked={toggleLocChecked}
        canDelete={canDelete}
        isDarkMode={isDarkMode}
      />
    </div>
  );
}

export default App;

// src/App.vue
<template>
  <div class="padCom">
    <h1 style="text-align: center;">Location App</h1>
    <div class="input-group mb-3">
      <GMapAutocomplete
        class="form-control"
        @place_changed="setPlace"
        @keyup.enter="addLoc"
        placeholder="Enter Location"/>
      <button class="btn btn-outline-primary" type="button" @click="addLoc">Add Location</button>
      <button class="btn btn-outline-secondary" type="button" @click="getCurrentPosition">Get Current Posistion</button>
    </div>
    <transition name="fade" mode="out-in">
      <div v-if="warningMsg" class="alert alert-warning d-flex align-items-center" role="alert">
        Location entered is not found. Please select a location from dropdown
      </div>
    </transition>
  </div>
  <MapApp :items="locItems" :center="center"/>
  <LocTable :items="locItems" @delLoc="delLoc" class="padCom"/>
</template>

<script>
import MapApp from './components/MapApp.vue'
import LocTable from './components/LocTable.vue'

import axios from 'axios'

const GOOGLE_MAP_API_KEY = 'AIzaSyDzHMfu1uVshFyDcUVtI2EDAgaX8CJ_5a0'

export default {
  name: 'App',
  components: {
    MapApp,
    LocTable
  },
  data() {
    return {
      searchTerm: '',
      locItems: [], // Array to store the added text
      center: { lat: 43.653226, lng: -79.3831843 },
      warningMsg: false
    };
  },
  methods: {
    setPlace(place) {
      this.searchTerm = place; // Save result when finished input a place
    },
    getCoordinates() {
      return new Promise(function(resolve, reject) {
        navigator.geolocation.getCurrentPosition(resolve, reject);
    })},
    async getCurrentPosition() {
      if (navigator.geolocation) {
        const { coords } = await this.getCoordinates();
        const { latitude, longitude } = coords;
        const pos = { lat: latitude, lng: longitude }
        const { data: currLocData } = await axios
          .get(`https://maps.googleapis.com/maps/api/geocode/json?latlng=${pos.lat},${pos.lng}&key=${GOOGLE_MAP_API_KEY}`)
        const now = (Date.now() / 1000).toFixed(0);
        const { data: timezone } = await axios
          .get(`https://maps.googleapis.com/maps/api/timezone/json?location=${pos.lat},${pos.lng}&timestamp=${now}&key=${GOOGLE_MAP_API_KEY}`)
        const { timeZoneName, dstOffset, rawOffset } = timezone;
        const localTime = new Date((Number(now) + dstOffset + rawOffset) * 1000);
        const localTimeStr = `${localTime.getUTCHours().toString().padStart(2, '0')}:${localTime.getUTCMinutes().toString().padStart(2, '0')}`
        this.locItems.push({ locName: currLocData.results[0].formatted_address, pos, timeZoneName, localTimeStr, checked: false });
        this.center = pos;
      } else {
        console.error("Geolocation is not supported by this browser.");
      }
    },
    async addLoc() {
      if (this.searchTerm && this.searchTerm.geometry) {
        // Get Latitude and Longtitude of the place
        const { lat, lng } = this.searchTerm.geometry.location;
        const pos = { lat: lat(), lng: lng() };
        // Get Timezone and Local Time of the place using lat and lng
        const now = (Date.now() / 1000).toFixed(0);
        const { data: timezone } = await axios
          .get(`https://maps.googleapis.com/maps/api/timezone/json?location=${pos.lat},${pos.lng}&timestamp=${now}&key=${GOOGLE_MAP_API_KEY}`)
        const { timeZoneName, dstOffset, rawOffset } = timezone;
        const localTime = new Date((Number(now) + dstOffset + rawOffset) * 1000);
        const localTimeStr = `${localTime.getUTCHours().toString().padStart(2, '0')}:${localTime.getUTCMinutes().toString().padStart(2, '0')}`
        this.locItems.push({ locName: this.searchTerm.name, pos, timeZoneName, localTimeStr, checked: false });
        this.center = pos;
      } else {
        this.warningMsg = true;
        setTimeout(() => {
          this.warningMsg = false
        }, 5000)
      }
    },
    delLoc() {
      this.locItems = this.locItems.filter((item) => !item.checked);
    },
  },
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  color: #2c3e50;
  text-align: center;
  margin-top: 60px;
  margin-bottom: 60px;
}
.padCom {
  padding-left: 5%;
  padding-right: 5%;
}
.fade-enter-active,
.fade-leave-active {
  transition: opacity 1.3s ease;
}

.fade-enter,
.fade-leave-to {
  opacity: 0;
}
</style>
